INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 1', 'Description of product 1', 1.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 2', 'Description of product 2', 2.00, 1.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 3', 'Description of product 3', 3.00, 2.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 4', 'Description of product 4', 4.00, 3.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 5', 'Description of product 5', 5.00, 4.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 6', 'Description of product 6', 6.00, 5.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 7', 'Description of product 7', 7.00, 6.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 8', 'Description of product 8', 8.00, 7.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 9', 'Description of product 9', 9.00, 8.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 10', 'Description of product 10', 10.00, 9.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 11', 'Description of product 11', 11.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 12', 'Description of product 12', 12.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 13', 'Description of product 13', 13.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 14', 'Description of product 14', 14.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 15', 'Description of product 15', 15.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 16', 'Description of product 16', 16.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 17', 'Description of product 17', 17.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 18', 'Description of product 18', 18.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 19', 'Description of product 19', 19.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 20', 'Description of product 20', 20.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 21', 'Description of product 21', 21.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, STOCK, IMAGE_URL) VALUES ('Product 22', 'Description of product 22', 22.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 23', 'Description of product 23', 23.00, 1.00, 13, '')

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, SALE_PRICE, STOCK, IMAGE_URL) VALUES ('Product 24', 'Description of product 24', 24.00, 11.00, 13, '')